import { ContaAcrescimo } from "./class/contaAcressimo";
import { ContaPf } from "./class/contaPF";
import { ContaPj } from "./class/contaPJ";

const user = new ContaPf(1 , "Rafael" , 10)
user.mostrarConta()
user.depositarDinheiro(50)
console.log('\n\n')
user.mostrarConta()
user.sacarDinheiro(25)
console.log('\n\n')
user.mostrarConta()
console.log('\n\n')
const userPj = new  ContaPj("EmpresaLTDA" , 20 , 34)
userPj.mostrarConta()
userPj.depositarDinheiro(70)
console.log('\n\n')
userPj.mostrarConta()
userPj.sacarDinheiro(30)
console.log('\n\n')
userPj.mostrarConta()
console.log('\n\n')
userPj.pegarEmpréstimos(100)
userPj.mostrarConta()
console.log('\n\n')
const contaAcrecimo = new ContaAcrescimo("Rafael" , 220)
contaAcrecimo.mostrarConta()
contaAcrecimo.depositarDinheiro(200)
console.log("\n\n")
contaAcrecimo.mostrarConta()
